### ISSUE TITLE
Support JupyterLab 3

### ISSUE THREAD

**Issue by dclong** [NERSC/jupyterlab-favorites#17]
JupyterLab 3 is out. It's great if this plugin can be updated to be compatible with jupyterlab 3.

**Comment by jasongrout** [comment]
A lot of people +1'd this issue. Is there anyone here that can volunteer to maintain this extension, or at least submit a PR for updating this?

**Comment by mlhenderson** [comment]
I will be submitting a PR to migrate this extension to JL3.
